### PR TITLE
Update the RPM to install the nvidia-xrun-pm systemd service.

### PR DESCRIPTION
**Pull request by LukeShortCloud**
This also changes the version to more-so align with the Arch Linux package by following the ISO date format and adds a changelog.

### CODE REVIEW

**Comment by michelesr** [comment]
It looks good, thanks for your contribution.

**Comment by LukeShortCloud** [comment]
Glad to help!

I just noticed that a few weeks ago the upstream [nvidia-xrun repository](https://github.com/Witko/nvidia-xrun) had an update to remove the dependency on `bbswitch`. It now uses a similar power management method that `nvidia-xrun-pm` does: https://github.com/Witko/nvidia-xrun/pull/90/commits/43735003aa38b884251243ec907519ebd68ca471

We could look into merging the `nvidia-xrun-pm` systemd service along with the Arch Linux package and updated RPM spec into the original repository. This would help prevent fragmentation and consolidate community contributions back into one repository.

**Comment by michelesr** [comment]
I was thinking the same, in fact I've opened an issue on the main
repository to discuss the possibility of merging the code in the original
project.

**Comment by michelesr** [comment]
From what I can see in Witko@4373500, the approach is a little bit different, the PCIe controller `0000:00:01.0` bus is targeted instead of the card `0000:01:00.0`.

We probably can add the systemd service to the main repository but we'll have to align it with the configuration file where you specify the bus id (currently is hardcoded).

@ekultails I'm not sure about the version number, currently is hardcoded to `20181128` so we must need to generate it dynamically (like it's done in the Arch Linux `PKGBUILD` `pkgver()` function).

Leaving the `PKGBUILD` in the repository for the main project doesn't really make sense as the package is available in [aur](https://aur.archlinux.org/packages/nvidia-xrun/)

**Comment by michelesr** [comment]
TODO:

- [ ] Verify the Witko's approach works fine
- [ ] Create a better systemd service that can read the bus id from the configuration file
- [ ] Fix the versioning in the RPM spec
- [ ] Get rid of the archlinux folder
- [ ] Open the PR

**Comment by samuelstjean** [comment]
Looks like there is no issues button somehow, but indeed not hardcoding the bus id would be a good idea, mine is on number 2 for example and not the hardcoded one somehow.

**Comment by michelesr** [comment]
@samuelstjean I added the issues button... sorry about that. I'll see if I can somehow merge the latest changes from the upstream while keeping the logic intact.

**Comment by samuelstjean** [comment]
no worries, but indeed reunification as you have mentioned left and right would be a good idea, seems like the original also went the no bumblebee way. It's kind of sad that people left and right have to fix huge issues for everyone with a laptop using optimus instead of major upstream people, but go guys!

**Pull request merged**
